name: Deploy Fullstack App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Add EC2 host to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy and Setup on EC2
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Update system
          sudo apt update

          # Install required packages
          sudo apt install -y nginx nodejs npm git

          # Clone or update repo
          if [ ! -d node-react-ecommerce ]; then
            git clone https://github.com/NaveedAliKhan4177/node-react-ecommerce.git
          else
            cd node-react-ecommerce && git pull origin main && cd ..
          fi

          # Install PM2 globally (if not installed)
          sudo npm install -g pm2

          # === FRONTEND ===
          cd /home/ubuntu/node-react-ecommerce/frontend
          npm install
          npm run build
          sudo rm -rf /var/www/html/*
          sudo cp -r build/* /var/www/html/

          # === BACKEND ===
          cd /home/ubuntu/node-react-ecommerce/backend
          npm install
          chmod +x server.mjs

          # Kill old app and restart with PM2 using .mjs format
          pm2 delete backend-app || true
          pm2 start server.mjs --name backend-app --interpreter node
          pm2 save
          pm2 startup | grep sudo | bash
        EOF
