name: Deploy Node + React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Clone or update repo
            rm -rf node-react-ecommerce || true
            git clone https://github.com/NaveedAliKhan4177/node-react-ecommerce.git
            cd node-react-ecommerce

            # Install & start backend
            cd backend
            npm install
            pm2 delete backend || true
            pm2 start index.js --name backend
            cd ..

            # Install & build frontend
            cd frontend
            npm install
            npm run build

            # Copy build to Nginx
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/
            sudo systemctl restart nginx
          EOF
